/**
 * CIVICA ગુજરાત - Urban Intelligence, Gujarat Municipal & Officer Data Model
 * Municipalities: AMC (Ahmedabad), SMC (Surat), VMC (Vadodara), RMC (Rajkot), GMC (Gandhinagar)
 */

const GUJARAT_CIVIC_DATA = {
  activeCity: {
    id: "AMC",
    name: "Ahmedabad Municipal Corporation",
    shortName: "AMC Ahmedabad",
    zone: "West Zone",
    ward: "Ward 7 · Navrangpura",
    centerCoords: [23.0375, 72.5625]
  },

  cities: [
    { id: "AMC", name: "AMC Ahmedabad", gujarati: "અમદાવાદ મહાનગરપાલિકા", zone: "West Zone", ward: "Ward 7 · Navrangpura", coords: [23.0375, 72.5625] },
    { id: "SMC", name: "SMC Surat", gujarati: "સુરત મહાનગરપાલિકા", zone: "Athwa Zone", ward: "Ward 12 · Vesu", coords: [21.1702, 72.8311] },
    { id: "VMC", name: "VMC Vadodara", gujarati: "વડોદરા મહાનગરપાલિકા", zone: "Central Zone", ward: "Ward 4 · Alkapuri", coords: [22.3072, 73.1812] },
    { id: "RMC", name: "RMC Rajkot", gujarati: "રાજકોટ મહાનગરપાલિકા", zone: "West Zone", ward: "Ward 9 · Kalawad Road", coords: [22.3039, 70.8022] },
    { id: "GMC", name: "GMC Gandhinagar", gujarati: "ગાંધીનગર મહાનગરપાલિકા", zone: "Sector Zone", ward: "Sector 7 · Sachivalay", coords: [23.2156, 72.6369] }
  ],

  // 6 Common Civic Categories
  issueTypes: [
    { id: "streetlight", name: "Streetlight", gujarati: "સ્ટ્રીટલાઈટ", icon: "💡", dept: "Light & Electrical" },
    { id: "pothole", name: "Pothole", gujarati: "ખાડા (Pothole)", icon: "🚧", dept: "Public Works & Roads" },
    { id: "garbage", name: "Garbage", gujarati: "કચરો / ગંદકી", icon: "🗑️", dept: "Solid Waste Management" },
    { id: "waterlogging", name: "Waterlogging", gujarati: "ચોમાસુ પાણી ભરાવ (Monsoon)", icon: "🌊", dept: "Monsoon & Drainage" },
    { id: "brts", name: "BRTS / Bus Stop", gujarati: "બીઆરટીએસ / બસ સ્ટેન્ડ", icon: "🚌", dept: "Transit Authority" },
    { id: "water", name: "Water Supply", gujarati: "પાણી પુરવઠો", icon: "💧", dept: "Hydraulics & Water Works" },
    { id: "others", name: "Others", gujarati: "અન્ય સમસ્યા", icon: "📋", dept: "General Administration & Citizen Redressal" }
  ],

  // Gujarati / English / Hindi Status Mapping
  statusMap: {
    received: { en: "Received", gu: "પ્રાપ્ત", hi: "प्राप्त", class: "status-received" },
    assigned: { en: "Assigned", gu: "સોંપાયેલ", hi: "सौंपा गया", class: "status-assigned" },
    in_progress: { en: "In Progress", gu: "પ્રગતિમાં", hi: "प्रगति में", class: "status-inprogress" },
    resolved: { en: "Resolved", gu: "ઉકેલાયેલ", hi: "समाधान पूर्ण", class: "status-resolved" },
    need_info: { en: "Need Info", gu: "માહિતી જોઈએ છે", hi: "जानकारी आवश्यक", class: "status-needinfo" },
    closed: { en: "Closed", gu: "બંધ કરેલ", hi: "बंद", class: "status-closed" },
    new: { en: "New", gu: "નવી", hi: "नई", class: "status-new" }
  },

  // Officer Profile
  officerProfile: {
    name: "R. Patel",
    title: "Ward Officer & Electrical Supervisor",
    role: "AMC Ward 7",
    department: "AMC Street Lighting & Roads",
    avatar: "RP"
  },

  // Officer Dashboard Metrics
  officerKPIs: {
    openTickets: 28,
    dueToday: 9,
    needCitizenReply: 6,
    resolvedThisWeek: 14,
    mttrHours: 3.8,
    crowdsourceAccuracy: "92.4%",
    activeCrews: 6
  },

  // Shift Actions Checklist
  shiftActions: [
    { id: 1, text: "Assign 4 new tickets to Ward Highway & Electrical crews", done: false },
    { id: 2, text: "Inspect CG Road streetlight #18492 & verify ₹50 refund", done: true },
    { id: 3, text: "Send Gujarati updates to 3 citizen tickets", done: false },
    { id: 4, text: "Monsoon pin review (Law Garden & Mithakhali underpasses)", done: false },
    { id: 5, text: "Crew 14 overtime authorization for night shift patching", done: false }
  ],

  // Officer Complaint Inbox List
  inboxTickets: [
    { id: "18492", fullId: "GJ-AMC-2026-18492", citizen: "K. Shah", issue: "Streetlight", place: "CG Road", age: "4d", status: "in_progress", statusLabel: "In progress", filterCategory: "assigned_to_me", priority: true, slaRisk: false, isMonsoon: false, severity: "routine" },
    { id: "18501", fullId: "GJ-AMC-2026-18501", citizen: "M. Joshi", issue: "Waterlogging", place: "Law Garden", age: "2h", status: "new", statusLabel: "New", filterCategory: "new", priority: true, slaRisk: false, isMonsoon: true, severity: "critical" },
    { id: "18470", fullId: "GJ-AMC-2026-18470", citizen: "A. Mehta", issue: "Pothole", place: "Ashram Road", age: "1d", status: "assigned", statusLabel: "Assigned", filterCategory: "assigned_to_me", priority: true, slaRisk: false, isMonsoon: false, severity: "high" },
    { id: "18388", fullId: "GJ-AMC-2026-18388", citizen: "S. Rana", issue: "Garbage", place: "Pol lane 12", age: "6d", status: "need_info", statusLabel: "Need info", filterCategory: "assigned_to_me", priority: true, slaRisk: true, isMonsoon: false, severity: "routine" },
    { id: "18312", fullId: "GJ-AMC-2026-18312", citizen: "P. Desai", issue: "Water supply", place: "Naranpura", age: "3d", status: "assigned", statusLabel: "Assigned", filterCategory: "all", priority: false, slaRisk: false, isMonsoon: false, severity: "high" },
    { id: "18290", fullId: "GJ-AMC-2026-18290", citizen: "R. Vyas", issue: "BRTS stop", place: "Iskcon", age: "5d", status: "in_progress", statusLabel: "In progress", filterCategory: "all", priority: false, slaRisk: true, isMonsoon: false, severity: "high" }
  ],

  // Civic Anti-Spam Wallet & Security Deposit State
  citizenWallet: {
    balance: 150.00,
    currency: "₹",
    depositFee: 50.00,
    transactions: [
      { id: "TX-9821", type: "credit", title: "Initial Civic Top-up", amount: 150.00, date: "10 Sep 2026", method: "FamPay UPI", status: "completed" },
      { id: "TX-9822", type: "held", title: "Security Deposit (Escrow) · #18492 Streetlight", amount: 50.00, date: "12 Sep 2026", method: "Civic Wallet", status: "held", ticketId: "GJ-AMC-2026-18492" }
    ]
  },

  // Detailed Complaints Model (Linked between Citizen, Officer, and Command Center)
  complaints: [
    {
      id: "GJ-AMC-2026-18492",
      shortId: "18492",
      citizen: "K. Shah",
      citizenPhone: "98765 43210",
      title: "Streetlight out — CG Road, Navrangpura",
      type: "streetlight",
      categoryName: "Streetlight",
      categoryGu: "સ્ટ્રીટલાઈટ",
      location: "CG Road, Navrangpura",
      coords: [23.0372, 72.5615],
      distance: "120 m",
      ward: "Ward 7",
      zone: "West Zone",
      agency: "AMC Street Lighting",
      department: "Light & Electrical",
      status: "in_progress",
      stage: "dispatched", // 'backlog' | 'investigation' | 'dispatched' | 'resolved'
      severity: "routine",
      depositAmount: 50,
      depositStatus: "held", // 'held' | 'refunded' | 'forfeited'
      depositMethod: "Civic Wallet",
      depositTxId: "ESC-18492",
      filedDate: "12 Sep 2026",
      dueDate: "20 Sep 2026",
      slaDate: "20 Sep",
      confirmations: 14,
      assignedCrew: "Street Lighting Crew 14 — West Zone",
      note: "AMC electrical crew inspected the pole near Law Garden crossing. Replacement fixture arrives 19 Sep. You will get a Gujarati SMS when the light is back on. — R. Patel",
      steps: [
        { label: "Received", labelGu: "પ્રાપ્ત", date: "12 Sep 10:14", completed: true },
        { label: "Assigned", labelGu: "સોંપાયેલ", date: "13 Sep Crew 14", completed: true },
        { label: "In progress", labelGu: "પ્રગતિમાં", date: "16 Sep Fixture", completed: true, active: true },
        { label: "Resolved", labelGu: "ઉકેલાયેલ", date: "Due 20 Sep", completed: false }
      ],
      photoUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "GJ-AMC-2026-18501",
      shortId: "18501",
      citizen: "M. Joshi",
      citizenPhone: "98251 12345",
      title: "Monsoon Waterlogging · Law Garden subway",
      type: "waterlogging",
      categoryName: "Waterlogging",
      categoryGu: "પાણી ભરાવ",
      location: "Law Garden underpass",
      coords: [23.0284, 72.5562],
      distance: "400 m",
      ward: "Ward 7",
      zone: "West Zone",
      agency: "AMC Storm Water Drainage",
      department: "Monsoon & Drainage",
      status: "new",
      stage: "backlog",
      severity: "critical",
      depositAmount: 50,
      depositStatus: "held",
      depositMethod: "Paytm UPI",
      depositTxId: "ESC-18501",
      filedDate: "Today 08:30",
      dueDate: "Today 18:00",
      slaDate: "Today (2h SLA)",
      confirmations: 38,
      assignedCrew: "Pending Assignment",
      note: "New monsoon waterlogging alert flagged by resident. Dewatering tractor pump request generated.",
      steps: [
        { label: "Received", labelGu: "પ્રાપ્ત", date: "Today 08:30", completed: true, active: true },
        { label: "Assigned", labelGu: "સોંપાયેલ", date: "Pending", completed: false },
        { label: "In progress", labelGu: "પ્રગતિમાં", date: "Pending", completed: false },
        { label: "Resolved", labelGu: "ઉકેલાયેલ", date: "Due Today", completed: false }
      ],
      photoUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "GJ-AMC-2026-18470",
      shortId: "18470",
      citizen: "A. Mehta",
      citizenPhone: "98980 98765",
      title: "Deep Pothole on Commuter Lane · Ashram Road",
      type: "pothole",
      categoryName: "Pothole",
      categoryGu: "ખાડો",
      location: "Ashram Road · near Vadaj Circle",
      coords: [23.0489, 72.5714],
      distance: "240 m",
      ward: "Ward 7",
      zone: "West Zone",
      agency: "AMC Road Project Dept",
      department: "Public Works & Roads",
      status: "assigned",
      stage: "investigation",
      severity: "high",
      depositAmount: 50,
      depositStatus: "held",
      depositMethod: "Civic Wallet",
      depositTxId: "ESC-18470",
      filedDate: "Yesterday",
      dueDate: "Tomorrow",
      slaDate: "19 Sep (24h SLA)",
      confirmations: 22,
      assignedCrew: "Road Maintenance Crew 08",
      note: "Assigned to Crew 08. Cold-mix patch truck scheduled for night shift deployment.",
      steps: [
        { label: "Received", labelGu: "પ્રાપ્ત", date: "Yesterday 09:30", completed: true },
        { label: "Assigned", labelGu: "સોંપાયેલ", date: "Yesterday 14:00 Crew 08", completed: true, active: true },
        { label: "In progress", labelGu: "પ્રગતિમાં", date: "Scheduled tonight", completed: false },
        { label: "Resolved", labelGu: "ઉકેલાયેલ", date: "Due 19 Sep", completed: false }
      ],
      photoUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "GJ-AMC-2026-18388",
      shortId: "18388",
      citizen: "S. Rana",
      citizenPhone: "97123 45678",
      title: "Bulk Garbage in Pol lane 12",
      type: "garbage",
      categoryName: "Garbage",
      categoryGu: "કચરો",
      location: "Pol lane 12, Navrangpura",
      coords: [23.0336, 72.5601],
      distance: "350 m",
      ward: "Ward 7",
      zone: "West Zone",
      agency: "AMC Solid Waste",
      department: "Solid Waste Management",
      status: "need_info",
      stage: "investigation",
      severity: "routine",
      depositAmount: 50,
      depositStatus: "held",
      depositMethod: "PhonePe",
      depositTxId: "ESC-18388",
      filedDate: "6 days ago",
      dueDate: "Overdue (SLA Risk)",
      slaDate: "15 Sep",
      confirmations: 9,
      assignedCrew: "Sanitation Supervisor Vyas",
      note: "AMC supervisor visited the lane. Commercial gate was locked. Requested citizen to provide phone of gatekeeper or night access time.",
      steps: [
        { label: "Received", labelGu: "પ્રાપ્ત", date: "6d ago", completed: true },
        { label: "Assigned", labelGu: "સોંપાયેલ", date: "5d ago", completed: true },
        { label: "Need Info", labelGu: "માહિતી જોઈએ છે", date: "Waiting on resident", completed: true, active: true },
        { label: "Resolved", labelGu: "ઉકેલાયેલ", date: "Pending", completed: false }
      ],
      photoUrl: "https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "GJ-AMC-2026-18290",
      shortId: "18290",
      citizen: "R. Vyas",
      citizenPhone: "98240 55112",
      title: "BRTS Shelter Glass Damage · Iskcon Cross Roads",
      type: "brts",
      categoryName: "BRTS / Bus Stop",
      categoryGu: "બીઆરટીએસ",
      location: "Iskcon Cross Roads, SG Highway",
      coords: [23.0298, 72.5065],
      distance: "2.8 km",
      ward: "Ward 8",
      zone: "South West Zone",
      agency: "Janmarg BRTS Authority",
      department: "Transit Authority",
      status: "in_progress",
      stage: "dispatched",
      severity: "high",
      depositAmount: 50,
      depositStatus: "refunded",
      depositMethod: "Civic Wallet",
      depositTxId: "ESC-18290",
      filedDate: "5 days ago",
      dueDate: "Tomorrow",
      slaDate: "19 Sep",
      confirmations: 31,
      assignedCrew: "Transit Maintenance Unit 2",
      note: "Verified by Transit Inspector. Replacement safety glass framed. Deposit refunded to citizen wallet.",
      steps: [
        { label: "Received", labelGu: "પ્રાપ્ત", date: "5d ago", completed: true },
        { label: "Assigned", labelGu: "સોંપાયેલ", date: "4d ago", completed: true },
        { label: "In progress", labelGu: "પ્રગતિમાં", date: "In progress", completed: true, active: true },
        { label: "Resolved", labelGu: "ઉકેલાયેલ", date: "Due 19 Sep", completed: false }
      ],
      photoUrl: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=600&q=80"
    },
    {
      id: "GJ-AMC-2026-18155",
      shortId: "18155",
      citizen: "D. Parikh",
      citizenPhone: "99090 11223",
      title: "Water Contamination / Low Pressure · Paldi",
      type: "water",
      categoryName: "Water Supply",
      categoryGu: "પાણી પુરવઠો",
      location: "Near Mahalaxmi Cross Roads, Paldi",
      coords: [23.0125, 72.5638],
      distance: "1.4 km",
      ward: "Ward 6",
      zone: "West Zone",
      agency: "AMC Hydraulics Dept",
      department: "Hydraulics & Water Works",
      status: "resolved",
      stage: "resolved",
      severity: "critical",
      depositAmount: 50,
      depositStatus: "refunded",
      depositMethod: "Civic Wallet",
      depositTxId: "ESC-18155",
      filedDate: "3 days ago",
      dueDate: "Completed",
      slaDate: "Resolved within 4h SLA",
      confirmations: 45,
      assignedCrew: "Hydraulics Rapid Response Van 04",
      note: "Submain valve repaired. Water chlorine test verified potable. ₹50 security deposit refunded to resident.",
      steps: [
        { label: "Received", labelGu: "પ્રાપ્ત", date: "3d ago", completed: true },
        { label: "Assigned", labelGu: "સોંપાયેલ", date: "3d ago", completed: true },
        { label: "In progress", labelGu: "પ્રગતિમાં", date: "3d ago", completed: true },
        { label: "Resolved", labelGu: "ઉકેલાયેલ", date: "Verified Resolved", completed: true, active: true }
      ],
      photoUrl: "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=600&q=80"
    }
  ],

  // Ready Report Message Templates
  reportTemplates: {
    parts_ordered: {
      title: "Parts ordered",
      subtext: "Give expected date",
      gu: "નમસ્તે {citizen},\n\nAMC વોર્ડ 7 એ તમારી {issue} ફરિયાદ {id} તપાસી છે. નવી ફિક્સચર 19 સપ્ટેમ્બરે આવશે. લાઇટ ચાલુ થાય ત્યારે SMS આવશે.\n\n— {officer}, AMC Street Lighting",
      en: "Namaste {citizen},\n\nAMC Ward 7 inspected your {issue} complaint {id}. Replacement parts ordered, expected on 19 Sep. You will receive an SMS when service is restored.\n\n— {officer}, AMC Street Lighting"
    },
    work_started: {
      title: "Work started",
      subtext: "Crew reached the site",
      gu: "નમસ્તે {citizen},\n\nAMC ફિલ્ડ ક્રૂ 14 તમારી {issue} ફરિયાદ {id} પર CG Road પહોંચી ગઈ છે અને કામગીરી શરૂ કરી દીધી છે.\n\n— {officer}, AMC Ward 7",
      en: "Namaste {citizen},\n\nAMC Field Crew 14 has arrived on site for your {issue} complaint {id} and repair work has commenced.\n\n— {officer}, AMC Ward 7"
    },
    need_photo: {
      title: "Need photo",
      subtext: "Ask citizen for more",
      gu: "નમસ્તે {citizen},\n\nતમારી ફરિયાદ {id} ની ઝડપી તપાસ માટે કૃપા કરીને પોલ નંબર અથવા રાત્રિ સમયનો ફોટો અપલોડ કરવા વિનંતી છે.\n\n— {officer}, AMC Ward 7",
      en: "Namaste {citizen},\n\nTo expedite your complaint {id}, please upload a clear night photo showing the pole identification plate.\n\n— {officer}, AMC Ward 7"
    },
    resolved: {
      title: "Resolved",
      subtext: "Light is working",
      gu: "નમસ્તે {citizen},\n\nતમારી {issue} ફરિયાદ {id} સફળતાપૂર્વક પૂર્ણ થઈ ગઈ છે. લાઇટ કાર્યરત છે. જો હજુ કોઈ સમસ્યા હોય તો તમે 7 દિવસમાં ફરિયાદ ફરી ખોલી શકો છો.\n\n— {officer}, AMC Ward 7",
      en: "Namaste {citizen},\n\nYour {issue} complaint {id} has been resolved and verified by supervisor. If issue persists, you may reopen within 7 days.\n\n— {officer}, AMC Ward 7"
    },
    not_municipal: {
      title: "Not municipal",
      subtext: "Send to GEB / police",
      gu: "નમસ્તે {citizen},\n\nઆ પોલ UGVCL/GEB હાઇ-ટેન્શન લાઇન સાથે જોડાયેલ છે. ફરિયાદ વીજ કંપની હેલ્પલાઇન 19122 પર ફોરવર્ડ કરવામાં આવી છે.\n\n— {officer}, AMC Ward 7",
      en: "Namaste {citizen},\n\nThis infrastructure falls under the state electricity board (UGVCL). Your report has been routed to Helpline 19122.\n\n— {officer}, AMC Ward 7"
    }
  },

  // Ward 7 Public Weekly Report
  wardWeeklyReport: {
    ward: "Ward 7",
    period: "This week Ward 7",
    summary: {
      filed: 41,
      resolved: 33,
      open: 8,
      acknowledgedPct: "98%"
    },
    topIssues: [
      { name: "Streetlights", count: 14 },
      { name: "Potholes", count: 9 },
      { name: "Waterlogging", count: 7 },
      { name: "SWM (Solid Waste)", count: 6 }
    ],
    citizenUpdates: {
      total: 52,
      gujaratiMessages: 52,
      whatsapp: 40,
      smsOnly: 12
    },
    slaWatch: {
      nearBreach: 2,
      assignedCrew: "Both assigned to Crew 14"
    }
  },

  // BRTS / Metro Information
  transit: [
    { id: "brts-janmarg", name: "Janmarg Green Line (BRTS)", nameGu: "જનમાર્ગ ગ્રીન લાઇન (BRTS)", status: "on time", eta: "4 min", corridor: "RTO Circle ↔ Maninagar via CG Road", crowd: "Normal (55%)", delayMinutes: 2 },
    { id: "metro-ahmedabad", name: "Ahmedabad Metro (North-South)", nameGu: "અમદાવાદ મેટ્રો (ઉત્તર-દક્ષિણ)", status: "on time", eta: "7 min", corridor: "APMC → Old High Court ↔ Motera", crowd: "Moderate (65%)", delayMinutes: 0 },
    { id: "metro-eastwest", name: "Ahmedabad Metro (East-West)", nameGu: "અમદાવાદ મેટ્રો (પૂર્વ-પશ્ચિમ)", status: "on time", eta: "9 min", corridor: "Thaltej ↔ Kalupur ↔ Vastral Gam", crowd: "Optimal (40%)", delayMinutes: 1 },
    { id: "gsrtc-bus", name: "GSRTC Intercity 18:40", nameGu: "જીએસઆરટીસી ઇન્ટરસિટી", status: "Boarding", eta: "18:40", corridor: "Geeta Mandir stand → Vadodara", crowd: "High Load", delayMinutes: 12 }
  ],

  // 15 Personalized Citizen Directories
  citizens: [
    { id: "CIT-001", folder: "citizen_01_aarav_patel", name: "Aarav Patel", email: "aarav.patel@suratcivic.in", phone: "9825100101", ward: "Ward 12 - Varachha", kyc: "Verified", karma: 340, tier: "Civic Hero", balance: 120, portalUrl: "citizens/citizen_01_aarav_patel/portal_view.html" },
    { id: "CIT-002", folder: "citizen_02_priya_sharma", name: "Priya Sharma", email: "priya.sharma@suratcivic.in", phone: "9825100102", ward: "Ward 04 - Athwa", kyc: "Verified", karma: 480, tier: "Civic Champion", balance: 210, portalUrl: "citizens/citizen_02_priya_sharma/portal_view.html" },
    { id: "CIT-003", folder: "citizen_03_rohit_verma", name: "Rohit Verma", email: "rohit.verma@suratcivic.in", phone: "9825100103", ward: "Ward 07 - Rander", kyc: "Verified", karma: 260, tier: "Active Citizen", balance: 85, portalUrl: "citizens/citizen_03_rohit_verma/portal_view.html" },
    { id: "CIT-004", folder: "citizen_04_ananya_deshmukh", name: "Ananya Deshmukh", email: "ananya.deshmukh@suratcivic.in", phone: "9825100104", ward: "Ward 09 - Katargam", kyc: "Verified", karma: 590, tier: "Civic Champion", balance: 310, portalUrl: "citizens/citizen_04_ananya_deshmukh/portal_view.html" },
    { id: "CIT-005", folder: "citizen_05_vikram_singh", name: "Vikram Singh", email: "vikram.singh@suratcivic.in", phone: "9825100105", ward: "Ward 15 - Udhna", kyc: "Verified", karma: 310, tier: "Active Citizen", balance: 140, portalUrl: "citizens/citizen_05_vikram_singh/portal_view.html" },
    { id: "CIT-006", folder: "citizen_06_neha_joshi", name: "Neha Joshi", email: "neha.joshi@suratcivic.in", phone: "9825100106", ward: "Ward 02 - Central", kyc: "Verified", karma: 410, tier: "Civic Hero", balance: 195, portalUrl: "citizens/citizen_06_neha_joshi/portal_view.html" },
    { id: "CIT-007", folder: "citizen_07_karan_mehta", name: "Karan Mehta", email: "karan.mehta@suratcivic.in", phone: "9825100107", ward: "Ward 08 - Limbayat", kyc: "Verified", karma: 220, tier: "Active Citizen", balance: 60, portalUrl: "citizens/citizen_07_karan_mehta/portal_view.html" },
    { id: "CIT-008", folder: "citizen_08_sneha_kulkarni", name: "Sneha Kulkarni", email: "sneha.kulkarni@suratcivic.in", phone: "9825100108", ward: "Ward 11 - Adajan", kyc: "Verified", karma: 530, tier: "Civic Champion", balance: 280, portalUrl: "citizens/citizen_08_sneha_kulkarni/portal_view.html" },
    { id: "CIT-009", folder: "citizen_09_dev_shah", name: "Dev Shah", email: "dev.shah@suratcivic.in", phone: "9825100109", ward: "Ward 06 - Piplod", kyc: "Verified", karma: 375, tier: "Civic Hero", balance: 150, portalUrl: "citizens/citizen_09_dev_shah/portal_view.html" },
    { id: "CIT-010", folder: "citizen_10_pooja_nair", name: "Pooja Nair", email: "pooja.nair@suratcivic.in", phone: "9825100110", ward: "Ward 03 - Vesu", kyc: "Verified", karma: 620, tier: "Civic Sentinel", balance: 390, portalUrl: "citizens/citizen_10_pooja_nair/portal_view.html" },
    { id: "CIT-011", folder: "citizen_11_amit_gupta", name: "Amit Gupta", email: "amit.gupta@suratcivic.in", phone: "9825100111", ward: "Ward 14 - Pandesara", kyc: "Verified", karma: 190, tier: "Active Citizen", balance: 50, portalUrl: "citizens/citizen_11_amit_gupta/portal_view.html" },
    { id: "CIT-012", folder: "citizen_12_kavita_reddy", name: "Kavita Reddy", email: "kavita.reddy@suratcivic.in", phone: "9825100112", ward: "Ward 05 - Majura", kyc: "Verified", karma: 345, tier: "Civic Hero", balance: 135, portalUrl: "citizens/citizen_12_kavita_reddy/portal_view.html" },
    { id: "CIT-013", folder: "citizen_13_rahul_choudhary", name: "Rahul Choudhary", email: "rahul.choudhary@suratcivic.in", phone: "9825100113", ward: "Ward 10 - Althan", kyc: "Verified", karma: 280, tier: "Active Citizen", balance: 90, portalUrl: "citizens/citizen_13_rahul_choudhary/portal_view.html" },
    { id: "CIT-014", folder: "citizen_14_divya_iyer", name: "Divya Iyer", email: "divya.iyer@suratcivic.in", phone: "9825100114", ward: "Ward 01 - City Light", kyc: "Verified", karma: 460, tier: "Civic Hero", balance: 220, portalUrl: "citizens/citizen_14_divya_iyer/portal_view.html" },
    { id: "CIT-015", folder: "citizen_15_manish_trivedi", name: "Manish Trivedi", email: "manish.trivedi@suratcivic.in", phone: "9825100115", ward: "Ward 13 - Dindoli", kyc: "Verified", karma: 510, tier: "Civic Champion", balance: 265, portalUrl: "citizens/citizen_15_manish_trivedi/portal_view.html" }
  ],

  // 4 Municipal Officer Admin Consoles
  admins: [
    { id: "ADM-001", folder: "admin_01_rajesh_parmar", name: "Rajesh Parmar", designation: "Senior Ward Commissioner", dept: "Central Admin & Operations", zone: "Central Zone", badge: "SMC-COMM-01", shift: "08:00 - 16:00", openTickets: 28, dueToday: 9, dashboardUrl: "admins/admin_01_rajesh_parmar/admin_dashboard.html" },
    { id: "ADM-002", folder: "admin_02_sunita_desai", name: "Sunita Desai", designation: "Executive Health & Sanitation Officer", dept: "Public Health & Waste", zone: "North Zone", badge: "SMC-HLTH-02", shift: "09:00 - 17:00", openTickets: 35, dueToday: 14, dashboardUrl: "admins/admin_02_sunita_desai/admin_dashboard.html" },
    { id: "ADM-003", folder: "admin_03_mahesh_solanki", name: "Mahesh Solanki", designation: "Chief Road & Infrastructure Engineer", dept: "Engineering & Drainage", zone: "West Zone", badge: "SMC-ENGR-03", shift: "10:00 - 18:00", openTickets: 41, dueToday: 12, dashboardUrl: "admins/admin_03_mahesh_solanki/admin_dashboard.html" },
    { id: "ADM-004", folder: "admin_04_farida_sheikh", name: "Farida Sheikh", designation: "Urban Grievance & Rapid Response Director", dept: "Command & Emergency Dispatch", zone: "South Zone", badge: "SMC-EMERG-04", shift: "14:00 - 22:00", openTickets: 52, dueToday: 18, dashboardUrl: "admins/admin_04_farida_sheikh/admin_dashboard.html" }
  ],

  // Citizen Saved Municipal Addresses Registry
  defaultAddresses: [
    {
      id: "ADDR-01",
      label: "Home",
      isPrimary: true,
      tag: "Primary Residence",
      recipient: "Priya Patel",
      phone: "+91 98765 43210",
      flatNo: "Flat 402, Shivalik Heights",
      street: "Near St. Xavier's Corner, CG Road",
      landmark: "Opp. Municipal Market",
      locality: "Navrangpura",
      ward: "Ward 7 · Navrangpura",
      zone: "West Zone",
      city: "AMC Ahmedabad",
      pincode: "380009",
      propertyUid: "AMC-W7-NV-4821",
      taxIndexNo: "07-04-192-0048",
      electricityNo: "10482910 (Torrent Power)",
      garbageSchedule: "Daily 07:30 AM (Shift A)",
      waterSupply: "06:00 AM - 08:30 AM (Active)",
      isVerified: true
    },
    {
      id: "ADDR-02",
      label: "Workplace",
      isPrimary: false,
      tag: "Commercial Office",
      recipient: "Priya Patel",
      phone: "+91 98765 43210",
      flatNo: "Suite 305, Pinnacle Business Hub",
      street: "Law Garden Cross Roads, Ellisbridge",
      landmark: "Behind Gujarat College Ground",
      locality: "Ellisbridge",
      ward: "Ward 7 · Navrangpura",
      zone: "West Zone",
      city: "AMC Ahmedabad",
      pincode: "380006",
      propertyUid: "AMC-W7-EB-9912",
      taxIndexNo: "07-08-301-1120",
      electricityNo: "10984421 (Torrent Power)",
      garbageSchedule: "Commercial SWM 09:30 AM",
      waterSupply: "Direct Municipal Pipeline",
      isVerified: true
    }
  ],

  // Comprehensive Municipal Complaint Resolution & SLA Audit Dataset
  resolutionAuditReports: [
    {
      id: "GJ-AMC-2026-18492",
      shortId: "18492",
      category: "streetlight",
      categoryName: "Streetlight",
      categoryIcon: "💡",
      department: "Light & Electrical",
      corporation: "AMC Ahmedabad",
      corpCode: "AMC",
      ward: "Ward 7 · Navrangpura",
      location: "CG Road, Opp Municipal Market",
      title: "Sodium vapor luminaire dead, low visibility",
      citizenName: "Kavita Shah",
      citizenPhone: "+91 98765 43210",
      citizenEmail: "kavita.shah@gujarat.in",
      citizenKarma: 340,
      filedDate: "2026-09-17T09:15:00",
      filedDateOnly: "2026-09-17",
      filedDateFormatted: "17 Sep 2026, 09:15 AM",
      status: "resolved",
      solvedBy: "R. Patel",
      solvedByDesignation: "Ward 7 Officer",
      solvedByDept: "Light & Electrical",
      resolvedDate: "2026-09-17T12:45:00",
      resolvedDateOnly: "2026-09-17",
      resolvedDateFormatted: "17 Sep 2026, 12:45 PM",
      timeTakenMinutes: 210,
      timeTakenFormatted: "3h 30m",
      timeTakenHours: 3.5,
      slaTargetHours: 6.0,
      slaStatus: "within_sla",
      resolutionSummary: "Replaced 120W LED driver ballast; illumination certified at 42 lux.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-SMC-2026-09412",
      shortId: "09412",
      category: "pothole",
      categoryName: "Road Pothole",
      categoryIcon: "🚧",
      department: "Public Works & Roads",
      corporation: "SMC Surat",
      corpCode: "SMC",
      ward: "Ward 04 · Athwa",
      location: "Athwa Gate Cross Road, Ring Road",
      title: "Severe bitumen subsidence near bridge ramp",
      citizenName: "Priya Sharma",
      citizenPhone: "+91 98251 00102",
      citizenEmail: "priya.sharma@suratcivic.in",
      citizenKarma: 480,
      filedDate: "2026-09-16T08:30:00",
      filedDateOnly: "2026-09-16",
      filedDateFormatted: "16 Sep 2026, 08:30 AM",
      status: "resolved",
      solvedBy: "Mahesh Solanki",
      solvedByDesignation: "Chief Road Engineer",
      solvedByDept: "Public Works & Roads",
      resolvedDate: "2026-09-16T13:45:00",
      resolvedDateOnly: "2026-09-16",
      resolvedDateFormatted: "16 Sep 2026, 01:45 PM",
      timeTakenMinutes: 315,
      timeTakenFormatted: "5h 15m",
      timeTakenHours: 5.25,
      slaTargetHours: 24.0,
      slaStatus: "within_sla",
      resolutionSummary: "Rapid cold-mix emulsion patching & vibratory roller compaction finished.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-SMC-2026-09388",
      shortId: "09388",
      category: "garbage",
      categoryName: "Solid Waste Management",
      categoryIcon: "🗑️",
      department: "Solid Waste Management",
      corporation: "SMC Surat",
      corpCode: "SMC",
      ward: "Ward 12 · Varachha",
      location: "Varachha Main Road, near Diamond Bourse",
      title: "Overflowing commercial garbage container",
      citizenName: "Aarav Patel",
      citizenPhone: "+91 98251 00101",
      citizenEmail: "aarav.patel@suratcivic.in",
      citizenKarma: 340,
      filedDate: "2026-09-15T11:00:00",
      filedDateOnly: "2026-09-15",
      filedDateFormatted: "15 Sep 2026, 11:00 AM",
      status: "resolved",
      solvedBy: "Sunita Desai",
      solvedByDesignation: "Health & Sanitation Officer",
      solvedByDept: "Solid Waste Management",
      resolvedDate: "2026-09-15T12:20:00",
      resolvedDateOnly: "2026-09-15",
      resolvedDateFormatted: "15 Sep 2026, 12:20 PM",
      timeTakenMinutes: 80,
      timeTakenFormatted: "1h 20m",
      timeTakenHours: 1.33,
      slaTargetHours: 4.0,
      slaStatus: "within_sla",
      resolutionSummary: "Hydraulic compactor truck dispatched; bin cleared and disinfectant lime sprayed.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-AMC-2026-18301",
      shortId: "18301",
      category: "waterlogging",
      categoryName: "Monsoon & Drainage",
      categoryIcon: "🌊",
      department: "Monsoon & Drainage",
      corporation: "AMC Ahmedabad",
      corpCode: "AMC",
      ward: "Ward 7 · Navrangpura",
      location: "Mithakhali Railway Underpass",
      title: "Storm water accumulation reaching 1.2 ft depth",
      citizenName: "M. Joshi",
      citizenPhone: "+91 98251 12345",
      citizenEmail: "m.joshi@gujarat.in",
      citizenKarma: 290,
      filedDate: "2026-09-14T07:45:00",
      filedDateOnly: "2026-09-14",
      filedDateFormatted: "14 Sep 2026, 07:45 AM",
      status: "resolved",
      solvedBy: "R. Patel",
      solvedByDesignation: "Ward 7 Officer",
      solvedByDept: "Monsoon & Drainage",
      resolvedDate: "2026-09-14T09:30:00",
      resolvedDateOnly: "2026-09-14",
      resolvedDateFormatted: "14 Sep 2026, 09:30 AM",
      timeTakenMinutes: 105,
      timeTakenFormatted: "1h 45m",
      timeTakenHours: 1.75,
      slaTargetHours: 3.0,
      slaStatus: "within_sla",
      resolutionSummary: "Twin 50HP dewatering pumps activated; storm silt traps cleaned; underpass clear.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-AMC-2026-18155",
      shortId: "18155",
      category: "water",
      categoryName: "Drinking Water Supply",
      categoryIcon: "💧",
      department: "Hydraulics & Water Works",
      corporation: "AMC Ahmedabad",
      corpCode: "AMC",
      ward: "Ward 7 · Navrangpura",
      location: "Near Mahalaxmi Cross Roads, Paldi",
      title: "Municipal drinking water pipeline low pressure",
      citizenName: "D. Parikh",
      citizenPhone: "+91 99090 11223",
      citizenEmail: "d.parikh@gujarat.in",
      citizenKarma: 410,
      filedDate: "2026-09-13T06:10:00",
      filedDateOnly: "2026-09-13",
      filedDateFormatted: "13 Sep 2026, 06:10 AM",
      status: "resolved",
      solvedBy: "Crew 14",
      solvedByDesignation: "Hydraulics Rapid Van",
      solvedByDept: "Hydraulics & Water Works",
      resolvedDate: "2026-09-13T09:40:00",
      resolvedDateOnly: "2026-09-13",
      resolvedDateFormatted: "13 Sep 2026, 09:40 AM",
      timeTakenMinutes: 210,
      timeTakenFormatted: "3h 30m",
      timeTakenHours: 3.5,
      slaTargetHours: 4.0,
      slaStatus: "within_sla",
      resolutionSummary: "Air-relief valve cleared on 250mm DI feeder line; 2.2 bar pressure restored.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-SMC-2026-09299",
      shortId: "09299",
      category: "brts",
      categoryName: "Transit Authority",
      categoryIcon: "🚌",
      department: "Transit Authority",
      corporation: "SMC Surat",
      corpCode: "SMC",
      ward: "Ward 01 · City Light",
      location: "City Light Bus Rapid Station #04",
      title: "Automated ticket barrier card reader malfunction",
      citizenName: "Divya Iyer",
      citizenPhone: "+91 98251 00114",
      citizenEmail: "divya.iyer@suratcivic.in",
      citizenKarma: 460,
      filedDate: "2026-09-12T14:20:00",
      filedDateOnly: "2026-09-12",
      filedDateFormatted: "12 Sep 2026, 02:20 PM",
      status: "resolved",
      solvedBy: "Farida Sheikh",
      solvedByDesignation: "Urban Grievance Director",
      solvedByDept: "Command & Emergency Dispatch",
      resolvedDate: "2026-09-12T17:00:00",
      resolvedDateOnly: "2026-09-12",
      resolvedDateFormatted: "12 Sep 2026, 05:00 PM",
      timeTakenMinutes: 160,
      timeTakenFormatted: "2h 40m",
      timeTakenHours: 2.67,
      slaTargetHours: 6.0,
      slaStatus: "within_sla",
      resolutionSummary: "Optical sensor recalibrated and RFID NFC firmware updated; gate verified.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-AMC-2026-17980",
      shortId: "17980",
      category: "streetlight",
      categoryName: "Streetlight",
      categoryIcon: "💡",
      department: "Light & Electrical",
      corporation: "AMC Ahmedabad",
      corpCode: "AMC",
      ward: "Ward 7 · Navrangpura",
      location: "Commerce College Road, Navrangpura",
      title: "Three consecutive streetlights flickering",
      citizenName: "Rohit Verma",
      citizenPhone: "+91 98251 00103",
      citizenEmail: "rohit.verma@suratcivic.in",
      citizenKarma: 260,
      filedDate: "2026-09-10T19:00:00",
      filedDateOnly: "2026-09-10",
      filedDateFormatted: "10 Sep 2026, 07:00 PM",
      status: "resolved",
      solvedBy: "R. Patel",
      solvedByDesignation: "Ward 7 Officer",
      solvedByDept: "Light & Electrical",
      resolvedDate: "2026-09-10T21:40:00",
      resolvedDateOnly: "2026-09-10",
      resolvedDateFormatted: "10 Sep 2026, 09:40 PM",
      timeTakenMinutes: 160,
      timeTakenFormatted: "2h 40m",
      timeTakenHours: 2.67,
      slaTargetHours: 6.0,
      slaStatus: "within_sla",
      resolutionSummary: "Loose phase connector at feeder junction box re-crimped and sealed.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 4
    },
    {
      id: "GJ-SMC-2026-09150",
      shortId: "09150",
      category: "pothole",
      categoryName: "Road Pothole",
      categoryIcon: "🚧",
      department: "Public Works & Roads",
      corporation: "SMC Surat",
      corpCode: "SMC",
      ward: "Ward 02 · Central",
      location: "Ring Road Flyover Junction, Central",
      title: "Crater on right lane causing 2-wheeler hazard",
      citizenName: "Neha Joshi",
      citizenPhone: "+91 98251 00106",
      citizenEmail: "neha.joshi@suratcivic.in",
      citizenKarma: 410,
      filedDate: "2026-09-08T10:15:00",
      filedDateOnly: "2026-09-08",
      filedDateFormatted: "08 Sep 2026, 10:15 AM",
      status: "resolved",
      solvedBy: "Rajesh Parmar",
      solvedByDesignation: "Senior Ward Commissioner",
      solvedByDept: "Central Admin & Operations",
      resolvedDate: "2026-09-08T14:30:00",
      resolvedDateOnly: "2026-09-08",
      resolvedDateFormatted: "08 Sep 2026, 02:30 PM",
      timeTakenMinutes: 255,
      timeTakenFormatted: "4h 15m",
      timeTakenHours: 4.25,
      slaTargetHours: 24.0,
      slaStatus: "within_sla",
      resolutionSummary: "Filled with bitumen mastic and road traffic cones deployed until set.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-VMC-2026-04210",
      shortId: "04210",
      category: "garbage",
      categoryName: "Solid Waste Management",
      categoryIcon: "🗑️",
      department: "Solid Waste Management",
      corporation: "VMC Vadodara",
      corpCode: "VMC",
      ward: "Ward 4 · Alkapuri",
      location: "RC Dutt Road, Alkapuri",
      title: "Green waste debris blocking pedestrian pathway",
      citizenName: "Vikram Singh",
      citizenPhone: "+91 98251 00105",
      citizenEmail: "vikram.singh@suratcivic.in",
      citizenKarma: 310,
      filedDate: "2026-09-06T15:00:00",
      filedDateOnly: "2026-09-06",
      filedDateFormatted: "06 Sep 2026, 03:00 PM",
      status: "resolved",
      solvedBy: "Sunita Desai",
      solvedByDesignation: "Health & Sanitation Officer",
      solvedByDept: "Solid Waste Management",
      resolvedDate: "2026-09-06T17:15:00",
      resolvedDateOnly: "2026-09-06",
      resolvedDateFormatted: "06 Sep 2026, 05:15 PM",
      timeTakenMinutes: 135,
      timeTakenFormatted: "2h 15m",
      timeTakenHours: 2.25,
      slaTargetHours: 4.0,
      slaStatus: "within_sla",
      resolutionSummary: "Tree branches shredded on-site; sidewalk cleared and swept clean.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-RMC-2026-03180",
      shortId: "03180",
      category: "waterlogging",
      categoryName: "Monsoon & Drainage",
      categoryIcon: "🌊",
      department: "Monsoon & Drainage",
      corporation: "RMC Rajkot",
      corpCode: "RMC",
      ward: "Ward 9 · Kalawad Road",
      location: "Near KKV Hall, Kalawad Road",
      title: "Clogged stormwater catch basin creating pool",
      citizenName: "Karan Mehta",
      citizenPhone: "+91 98251 00107",
      citizenEmail: "karan.mehta@suratcivic.in",
      citizenKarma: 220,
      filedDate: "2026-09-02T13:30:00",
      filedDateOnly: "2026-09-02",
      filedDateFormatted: "02 Sep 2026, 01:30 PM",
      status: "resolved",
      solvedBy: "Mahesh Solanki",
      solvedByDesignation: "Chief Road Engineer",
      solvedByDept: "Public Works & Roads",
      resolvedDate: "2026-09-02T16:00:00",
      resolvedDateOnly: "2026-09-02",
      resolvedDateFormatted: "02 Sep 2026, 04:00 PM",
      timeTakenMinutes: 150,
      timeTakenFormatted: "2h 30m",
      timeTakenHours: 2.5,
      slaTargetHours: 3.0,
      slaStatus: "within_sla",
      resolutionSummary: "Super suction jetting unit cleared 40kg polythene blockage; water drained.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 4
    },
    {
      id: "GJ-GMC-2026-01920",
      shortId: "01920",
      category: "streetlight",
      categoryName: "Streetlight",
      categoryIcon: "💡",
      department: "Light & Electrical",
      corporation: "GMC Gandhinagar",
      corpCode: "GMC",
      ward: "Sector 7 · Sachivalay",
      location: "Road 3, Sector 7 Sachivalay Circle",
      title: "Smart pole light sensor staying off after sunset",
      citizenName: "Sneha Kulkarni",
      citizenPhone: "+91 98251 00108",
      citizenEmail: "sneha.kulkarni@suratcivic.in",
      citizenKarma: 530,
      filedDate: "2026-08-28T18:45:00",
      filedDateOnly: "2026-08-28",
      filedDateFormatted: "28 Aug 2026, 06:45 PM",
      status: "resolved",
      solvedBy: "R. Patel",
      solvedByDesignation: "Ward 7 Officer",
      solvedByDept: "Light & Electrical",
      resolvedDate: "2026-08-28T21:10:00",
      resolvedDateOnly: "2026-08-28",
      resolvedDateFormatted: "28 Aug 2026, 09:10 PM",
      timeTakenMinutes: 145,
      timeTakenFormatted: "2h 25m",
      timeTakenHours: 2.42,
      slaTargetHours: 6.0,
      slaStatus: "within_sla",
      resolutionSummary: "Astronomical timer clock synched with central ICCC cloud server.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-SMC-2026-08840",
      shortId: "08840",
      category: "water",
      categoryName: "Drinking Water Supply",
      categoryIcon: "💧",
      department: "Hydraulics & Water Works",
      corporation: "SMC Surat",
      corpCode: "SMC",
      ward: "Ward 06 · Piplod",
      location: "Dumas Road, near RahulRaj Mall",
      title: "Turbid water observed in morning supply cycle",
      citizenName: "Dev Shah",
      citizenPhone: "+91 98251 00109",
      citizenEmail: "dev.shah@suratcivic.in",
      citizenKarma: 375,
      filedDate: "2026-08-22T07:15:00",
      filedDateOnly: "2026-08-22",
      filedDateFormatted: "22 Aug 2026, 07:15 AM",
      status: "resolved",
      solvedBy: "Farida Sheikh",
      solvedByDesignation: "Emergency Dispatch Director",
      solvedByDept: "Command & Emergency Dispatch",
      resolvedDate: "2026-08-22T10:45:00",
      resolvedDateOnly: "2026-08-22",
      resolvedDateFormatted: "22 Aug 2026, 10:45 AM",
      timeTakenMinutes: 210,
      timeTakenFormatted: "3h 30m",
      timeTakenHours: 3.5,
      slaTargetHours: 4.0,
      slaStatus: "within_sla",
      resolutionSummary: "Flushed dead-end hydrant; chlorine test registered safe at 0.5 ppm.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-SMC-2026-08711",
      shortId: "08711",
      category: "garbage",
      categoryName: "Solid Waste Management",
      categoryIcon: "🗑️",
      department: "Solid Waste Management",
      corporation: "SMC Surat",
      corpCode: "SMC",
      ward: "Ward 03 · Vesu",
      location: "VIP Road, Vesu",
      title: "Vegetable market organic waste piled on road",
      citizenName: "Pooja Nair",
      citizenPhone: "+91 98251 00110",
      citizenEmail: "pooja.nair@suratcivic.in",
      citizenKarma: 620,
      filedDate: "2026-08-16T10:00:00",
      filedDateOnly: "2026-08-16",
      filedDateFormatted: "16 Aug 2026, 10:00 AM",
      status: "resolved",
      solvedBy: "Sunita Desai",
      solvedByDesignation: "Health & Sanitation Officer",
      solvedByDept: "Solid Waste Management",
      resolvedDate: "2026-08-16T11:45:00",
      resolvedDateOnly: "2026-08-16",
      resolvedDateFormatted: "16 Aug 2026, 11:45 AM",
      timeTakenMinutes: 105,
      timeTakenFormatted: "1h 45m",
      timeTakenHours: 1.75,
      slaTargetHours: 4.0,
      slaStatus: "within_sla",
      resolutionSummary: "Dedicated organic transfer tipper dispatched; 2 metric tonnes collected.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-AMC-2026-17450",
      shortId: "17450",
      category: "pothole",
      categoryName: "Road Pothole",
      categoryIcon: "🚧",
      department: "Public Works & Roads",
      corporation: "AMC Ahmedabad",
      corpCode: "AMC",
      ward: "Ward 7 · Navrangpura",
      location: "Drive-In Road, Helmet Circle",
      title: "Rain-induced road erosion near bus bay",
      citizenName: "Amit Gupta",
      citizenPhone: "+91 98251 00111",
      citizenEmail: "amit.gupta@suratcivic.in",
      citizenKarma: 190,
      filedDate: "2026-08-10T11:30:00",
      filedDateOnly: "2026-08-10",
      filedDateFormatted: "10 Aug 2026, 11:30 AM",
      status: "resolved",
      solvedBy: "Mahesh Solanki",
      solvedByDesignation: "Chief Road Engineer",
      solvedByDept: "Public Works & Roads",
      resolvedDate: "2026-08-10T16:15:00",
      resolvedDateOnly: "2026-08-10",
      resolvedDateFormatted: "10 Aug 2026, 04:15 PM",
      timeTakenMinutes: 285,
      timeTakenFormatted: "4h 45m",
      timeTakenHours: 4.75,
      slaTargetHours: 24.0,
      slaStatus: "within_sla",
      resolutionSummary: "WMM base course layered and high-durability polymer patch applied.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-AMC-2026-17210",
      shortId: "17210",
      category: "streetlight",
      categoryName: "Streetlight",
      categoryIcon: "💡",
      department: "Light & Electrical",
      corporation: "AMC Ahmedabad",
      corpCode: "AMC",
      ward: "Ward 7 · Navrangpura",
      location: "Gulbai Tekra, Hollywood Basti road",
      title: "Dark spot near public school entrance",
      citizenName: "Kavita Reddy",
      citizenPhone: "+91 98251 00112",
      citizenEmail: "kavita.reddy@suratcivic.in",
      citizenKarma: 345,
      filedDate: "2026-08-03T20:10:00",
      filedDateOnly: "2026-08-03",
      filedDateFormatted: "03 Aug 2026, 08:10 PM",
      status: "resolved",
      solvedBy: "Crew 14",
      solvedByDesignation: "Electrical Rapid Squad",
      solvedByDept: "Light & Electrical",
      resolvedDate: "2026-08-03T22:30:00",
      resolvedDateOnly: "2026-08-03",
      resolvedDateFormatted: "03 Aug 2026, 10:30 PM",
      timeTakenMinutes: 140,
      timeTakenFormatted: "2h 20m",
      timeTakenHours: 2.33,
      slaTargetHours: 6.0,
      slaStatus: "within_sla",
      resolutionSummary: "New 90W LED bracket arm erected and wired to feeder 07-B.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-SMC-2026-08340",
      shortId: "08340",
      category: "waterlogging",
      categoryName: "Monsoon & Drainage",
      categoryIcon: "🌊",
      department: "Monsoon & Drainage",
      corporation: "SMC Surat",
      corpCode: "SMC",
      ward: "Ward 10 · Althan",
      location: "Althan Canal Road, near Althan Garden",
      title: "Water overflowing canal culvert onto road",
      citizenName: "Rahul Choudhary",
      citizenPhone: "+91 98251 00113",
      citizenEmail: "rahul.choudhary@suratcivic.in",
      citizenKarma: 280,
      filedDate: "2026-07-27T08:00:00",
      filedDateOnly: "2026-07-27",
      filedDateFormatted: "27 Jul 2026, 08:00 AM",
      status: "resolved",
      solvedBy: "Farida Sheikh",
      solvedByDesignation: "Emergency Dispatch Director",
      solvedByDept: "Command & Emergency Dispatch",
      resolvedDate: "2026-07-27T10:15:00",
      resolvedDateOnly: "2026-07-27",
      resolvedDateFormatted: "27 Jul 2026, 10:15 AM",
      timeTakenMinutes: 135,
      timeTakenFormatted: "2h 15m",
      timeTakenHours: 2.25,
      slaTargetHours: 3.0,
      slaStatus: "within_sla",
      resolutionSummary: "Culvert trash screen cleared; sluice gate opened to diversion channel.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-AMC-2026-16980",
      shortId: "16980",
      category: "garbage",
      categoryName: "Solid Waste Management",
      categoryIcon: "🗑️",
      department: "Solid Waste Management",
      corporation: "AMC Ahmedabad",
      corpCode: "AMC",
      ward: "Ward 7 · Navrangpura",
      location: "Behind Gujarat University Library",
      title: "Construction debris dumped along service road",
      citizenName: "Manish Trivedi",
      citizenPhone: "+91 98251 00115",
      citizenEmail: "manish.trivedi@suratcivic.in",
      citizenKarma: 510,
      filedDate: "2026-07-20T14:30:00",
      filedDateOnly: "2026-07-20",
      filedDateFormatted: "20 Jul 2026, 02:30 PM",
      status: "resolved",
      solvedBy: "Rajesh Parmar",
      solvedByDesignation: "Senior Ward Commissioner",
      solvedByDept: "Central Admin & Operations",
      resolvedDate: "2026-07-20T17:50:00",
      resolvedDateOnly: "2026-07-20",
      resolvedDateFormatted: "20 Jul 2026, 05:50 PM",
      timeTakenMinutes: 200,
      timeTakenFormatted: "3h 20m",
      timeTakenHours: 3.33,
      slaTargetHours: 4.0,
      slaStatus: "within_sla",
      resolutionSummary: "JCB loader lifted 4 tonnes C&D waste to Pirana processing plant.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 4
    },
    {
      id: "GJ-SMC-2026-07920",
      shortId: "07920",
      category: "streetlight",
      categoryName: "Streetlight",
      categoryIcon: "💡",
      department: "Light & Electrical",
      corporation: "SMC Surat",
      corpCode: "SMC",
      ward: "Ward 04 · Athwa",
      location: "Ghod Dod Road, Athwa",
      title: "Underground cable fault tripped 12 streetlights",
      citizenName: "Ananya Deshmukh",
      citizenPhone: "+91 98251 00104",
      citizenEmail: "ananya.deshmukh@suratcivic.in",
      citizenKarma: 590,
      filedDate: "2026-07-12T19:30:00",
      filedDateOnly: "2026-07-12",
      filedDateFormatted: "12 Jul 2026, 07:30 PM",
      status: "resolved",
      solvedBy: "R. Patel",
      solvedByDesignation: "Ward 7 Officer",
      solvedByDept: "Light & Electrical",
      resolvedDate: "2026-07-12T23:45:00",
      resolvedDateOnly: "2026-07-12",
      resolvedDateFormatted: "12 Jul 2026, 11:45 PM",
      timeTakenMinutes: 255,
      timeTakenFormatted: "4h 15m",
      timeTakenHours: 4.25,
      slaTargetHours: 6.0,
      slaStatus: "within_sla",
      resolutionSummary: "Cable thimble kit installed and circuit megger tested at 250MΩ.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-AMC-2026-16440",
      shortId: "16440",
      category: "pothole",
      categoryName: "Road Pothole",
      categoryIcon: "🚧",
      department: "Public Works & Roads",
      corporation: "AMC Ahmedabad",
      corpCode: "AMC",
      ward: "Ward 7 · Navrangpura",
      location: "St. Xavier's Corner, Navrangpura",
      title: "Broken manhole collar causing tyre blowouts",
      citizenName: "Kavita Shah",
      citizenPhone: "+91 98765 43210",
      citizenEmail: "kavita.shah@gujarat.in",
      citizenKarma: 340,
      filedDate: "2026-07-04T09:00:00",
      filedDateOnly: "2026-07-04",
      filedDateFormatted: "04 Jul 2026, 09:00 AM",
      status: "resolved",
      solvedBy: "Mahesh Solanki",
      solvedByDesignation: "Chief Road Engineer",
      solvedByDept: "Public Works & Roads",
      resolvedDate: "2026-07-04T12:30:00",
      resolvedDateOnly: "2026-07-04",
      resolvedDateFormatted: "04 Jul 2026, 12:30 PM",
      timeTakenMinutes: 210,
      timeTakenFormatted: "3h 30m",
      timeTakenHours: 3.5,
      slaTargetHours: 24.0,
      slaStatus: "within_sla",
      resolutionSummary: "Heavy-duty SFRC ductile cover and ring installed flush with asphalt.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-SMC-2026-07110",
      shortId: "07110",
      category: "waterlogging",
      categoryName: "Monsoon & Drainage",
      categoryIcon: "🌊",
      department: "Monsoon & Drainage",
      corporation: "SMC Surat",
      corpCode: "SMC",
      ward: "Ward 12 · Varachha",
      location: "Varachha Flyover Lower Carriage",
      title: "Heavy downpour waterlogging slowing transit",
      citizenName: "Aarav Patel",
      citizenPhone: "+91 98251 00101",
      citizenEmail: "aarav.patel@suratcivic.in",
      citizenKarma: 340,
      filedDate: "2026-06-25T11:00:00",
      filedDateOnly: "2026-06-25",
      filedDateFormatted: "25 Jun 2026, 11:00 AM",
      status: "resolved",
      solvedBy: "Farida Sheikh",
      solvedByDesignation: "Emergency Dispatch Director",
      solvedByDept: "Command & Emergency Dispatch",
      resolvedDate: "2026-06-25T12:50:00",
      resolvedDateOnly: "2026-06-25",
      resolvedDateFormatted: "25 Jun 2026, 12:50 PM",
      timeTakenMinutes: 110,
      timeTakenFormatted: "1h 50m",
      timeTakenHours: 1.83,
      slaTargetHours: 3.0,
      slaStatus: "within_sla",
      resolutionSummary: "Storm booster pump unit engaged; water drained into Tapi trunk main in 45m.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-VMC-2026-02980",
      shortId: "02980",
      category: "water",
      categoryName: "Drinking Water Supply",
      categoryIcon: "💧",
      department: "Hydraulics & Water Works",
      corporation: "VMC Vadodara",
      corpCode: "VMC",
      ward: "Ward 4 · Alkapuri",
      location: "Sayajigunj Circle",
      title: "Broken valve leaking drinking water on street",
      citizenName: "Priya Sharma",
      citizenPhone: "+91 98251 00102",
      citizenEmail: "priya.sharma@suratcivic.in",
      citizenKarma: 480,
      filedDate: "2026-06-18T07:20:00",
      filedDateOnly: "2026-06-18",
      filedDateFormatted: "18 Jun 2026, 07:20 AM",
      status: "resolved",
      solvedBy: "Crew 14",
      solvedByDesignation: "Hydraulics Rapid Van",
      solvedByDept: "Hydraulics & Water Works",
      resolvedDate: "2026-06-18T10:15:00",
      resolvedDateOnly: "2026-06-18",
      resolvedDateFormatted: "18 Jun 2026, 10:15 AM",
      timeTakenMinutes: 175,
      timeTakenFormatted: "2h 55m",
      timeTakenHours: 2.92,
      slaTargetHours: 4.0,
      slaStatus: "within_sla",
      resolutionSummary: "Sluice valve packing gland tightened and rubber gasket replaced.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-AMC-2026-15820",
      shortId: "15820",
      category: "garbage",
      categoryName: "Solid Waste Management",
      categoryIcon: "🗑️",
      department: "Solid Waste Management",
      corporation: "AMC Ahmedabad",
      corpCode: "AMC",
      ward: "Ward 7 · Navrangpura",
      location: "Law Garden Food Street",
      title: "Night food stalls plastic waste accumulation",
      citizenName: "Rohit Verma",
      citizenPhone: "+91 98251 00103",
      citizenEmail: "rohit.verma@suratcivic.in",
      citizenKarma: 260,
      filedDate: "2026-06-10T23:30:00",
      filedDateOnly: "2026-06-10",
      filedDateFormatted: "10 Jun 2026, 11:30 PM",
      status: "resolved",
      solvedBy: "Sunita Desai",
      solvedByDesignation: "Health & Sanitation Officer",
      solvedByDept: "Solid Waste Management",
      resolvedDate: "2026-06-11T01:15:00",
      resolvedDateOnly: "2026-06-11",
      resolvedDateFormatted: "11 Jun 2026, 01:15 AM",
      timeTakenMinutes: 105,
      timeTakenFormatted: "1h 45m",
      timeTakenHours: 1.75,
      slaTargetHours: 4.0,
      slaStatus: "within_sla",
      resolutionSummary: "Night sanitation sweep complete; twin litter bins positioned at entrance.",
      depositAmount: 50,
      depositStatus: "refunded",
      citizenRating: 5
    },
    {
      id: "GJ-AMC-2026-18501",
      shortId: "18501",
      category: "waterlogging",
      categoryName: "Monsoon & Drainage",
      categoryIcon: "🌊",
      department: "Monsoon & Drainage",
      corporation: "AMC Ahmedabad",
      corpCode: "AMC",
      ward: "Ward 7 · Navrangpura",
      location: "Law Garden underpass",
      title: "Monsoon Waterlogging · Law Garden subway",
      citizenName: "M. Joshi",
      citizenPhone: "+91 98251 12345",
      citizenEmail: "m.joshi@gujarat.in",
      citizenKarma: 290,
      filedDate: "2026-09-18T08:30:00",
      filedDateOnly: "2026-09-18",
      filedDateFormatted: "18 Sep 2026, 08:30 AM",
      status: "in_progress",
      solvedBy: "Pending Assignment",
      solvedByDesignation: "Assigned to Shift Crew",
      solvedByDept: "Monsoon & Drainage",
      resolvedDate: null,
      resolvedDateOnly: null,
      resolvedDateFormatted: "— Active in field —",
      timeTakenMinutes: null,
      timeTakenFormatted: "In Progress",
      timeTakenHours: null,
      slaTargetHours: 2.0,
      slaStatus: "within_sla",
      resolutionSummary: "Dewatering tractor pump en route; traffic diversion signage placed.",
      depositAmount: 50,
      depositStatus: "held",
      citizenRating: null
    },
    {
      id: "GJ-AMC-2026-18470",
      shortId: "18470",
      category: "pothole",
      categoryName: "Road Pothole",
      categoryIcon: "🚧",
      department: "Public Works & Roads",
      corporation: "AMC Ahmedabad",
      corpCode: "AMC",
      ward: "Ward 7 · Navrangpura",
      location: "Ashram Road · near Vadaj Circle",
      title: "Deep Pothole on Commuter Lane · Ashram Road",
      citizenName: "A. Mehta",
      citizenPhone: "+91 98980 98765",
      citizenEmail: "a.mehta@gujarat.in",
      citizenKarma: 310,
      filedDate: "2026-09-17T14:00:00",
      filedDateOnly: "2026-09-17",
      filedDateFormatted: "17 Sep 2026, 02:00 PM",
      status: "in_progress",
      solvedBy: "Crew 14",
      solvedByDesignation: "Road Maintenance Crew 08",
      solvedByDept: "Public Works & Roads",
      resolvedDate: null,
      resolvedDateOnly: null,
      resolvedDateFormatted: "— Scheduled tonight —",
      timeTakenMinutes: null,
      timeTakenFormatted: "In Progress",
      timeTakenHours: null,
      slaTargetHours: 24.0,
      slaStatus: "within_sla",
      resolutionSummary: "Cold-mix patch truck scheduled for night shift deployment.",
      depositAmount: 50,
      depositStatus: "held",
      citizenRating: null
    },
    {
      id: "GJ-AMC-2026-18388",
      shortId: "18388",
      category: "garbage",
      categoryName: "Solid Waste Management",
      categoryIcon: "🗑️",
      department: "Solid Waste Management",
      corporation: "AMC Ahmedabad",
      corpCode: "AMC",
      ward: "Ward 7 · Navrangpura",
      location: "Pol lane 12, Navrangpura",
      title: "Bulk Garbage in Pol lane 12 behind locked gate",
      citizenName: "S. Rana",
      citizenPhone: "+91 97123 45678",
      citizenEmail: "s.rana@gujarat.in",
      citizenKarma: 180,
      filedDate: "2026-09-12T10:00:00",
      filedDateOnly: "2026-09-12",
      filedDateFormatted: "12 Sep 2026, 10:00 AM",
      status: "sla_breach",
      solvedBy: "R. Patel",
      solvedByDesignation: "Ward 7 Officer",
      solvedByDept: "Solid Waste Management",
      resolvedDate: null,
      resolvedDateOnly: null,
      resolvedDateFormatted: "— Pending Citizen Access —",
      timeTakenMinutes: null,
      timeTakenFormatted: "Overdue (SLA Risk)",
      timeTakenHours: null,
      slaTargetHours: 4.0,
      slaStatus: "breached",
      resolutionSummary: "Commercial gate locked; resident notified via SMS for gatekeeper contact.",
      depositAmount: 50,
      depositStatus: "held",
      citizenRating: null
    }
  ]
};

window.GUJARAT_CIVIC_DATA = GUJARAT_CIVIC_DATA;
